lang: zh_CN
fb_username: 2401PT
fb_password: "980530"
fb_token: w9/BeLNV/9VE7diQXOsVytnWcol0+6Tv9jVJc1XBkIID0yPm10J4PPmZKrmoO2pfA8keGNPk8yTqdvdIqMH6THo14f96sz6Q4jTWyx1l8MJy58yxH0oFP9pRHyNmE0wHLOU9uAXJgVw5Khe6tpaBVbuP/w==
server_code: "96996635"
server_passwd: "286607"
respond_user: 2401PT
mute_world_chat: false
no_py_rpc: false
nbt_constructor_enable: false
fb_version: 1.4.0
fb_hash: ae097fc95d020eaaf28c92a9591798a41ab64077acdff72cf4008d35a533780c
fb_codename: Phoenix
